### ISSUE TITLE
Scrolling does not work in the details panel of a Subsystem

### ISSUE THREAD

**Issue by sinisastevanovic** [aquanox/SubsystemBrowserPlugin#1]
Awesome plugin! But I ran into an issue when trying to view details of a subsystem with many properties. 
If the panel expands beyond the borders of the window, I can't scroll to the properties outside of the view. 
The scrollbar appears for a frame or two and then disappears. 

![image](https://user-images.githubusercontent.com/20400957/164714672-57bcd3cd-6cfd-4636-b891-c9027ea811aa.png)

**Comment by MothDoctor** [comment]
@sinisastevanovic my PR should fix that :)

**Comment by sinisastevanovic** [comment]
Awesome!

**Comment by aquanox** [comment]
Thank you for PR. Merged.
