### ISSUE TITLE
Live Coding Reinstancing and HotReload tracking

### ISSUE THREAD

**Issue by aquanox** [aquanox/SubsystemBrowserPlugin#14]
This is list of my ideas to add some extra QOL to the plugin as there are things that could happen when Live Coding Reinstancing or HotReload  is being used when working with Unreal Engine (for example missing properties, not loading ini config).

It is possible to track object states for validity and display big red warning label that things may go bad until editor is restarted. 

* Can try track UStruct::PropertiesSize change (since we got a copy of subsystem info in SSDescriptor) validate with it
* Can try track special names like RELOADED or REINSTANCED  and similar 
* Can try track duplicated entries that could appear in certain situations
* Can hook to `FCoreUObjectDelegates::OnObjectsReinstanced`  to track that reinstancing was used
* maybe something else

**Comment by ameaninglessname** [comment]
Is there any cached `UObject` reference in code?(I'm going to use the plugin now) Which may cause the corruption when re-instancing

**Comment by aquanox** [comment]
> Is there any cached `UObject` reference in code?(I'm going to use the plugin now) Which may cause the corruption when re-instancing

It is not related to plugin but in general for Unreal Engine native development loop.

If you edit c++ code and change the memory layout or property reflection data you must close editor, build the project from IDE and launch again from IDE. Refer to this article. https://landelare.github.io/2023/01/07/cpp-speedrun.html#compiling for additional details.

I've created this ticket because I received more than several messages "why my properties disappear" or "why my properties do not show" with cause being use of Live Coding or HotReload after doing breaking changes in code and not restarting editor.

**Comment by aquanox** [comment]
Dropped
