### ISSUE TITLE
5.1 Missing include 

### ISSUE THREAD

**Issue by samrrr** [aquanox/SubsystemBrowserPlugin#6]
FEditorStyle undefined.
And:
FEditorStyle::Get() is deprecated, use FAppStyle::Get() instead.

**Comment by dynamiquel** [comment]
Adding `#include "EditorStyleSet.h"` in `SubsystemBrowserPanel.cpp` and `SubsystemBrowserColumn.cpp` fixed everything for me.
I know it's deprecated but I don't want to be messing around too much for something that should already be built in to the engine. Epic takes forever to remove deprecated features anyways.

**Comment by aquanox** [comment]
Fixed in 1.2.1
