### ISSUE TITLE
5.2 compile fails, and Market compatability

### ISSUE THREAD

**Issue by gardian06** [aquanox/SubsystemBrowserPlugin#9]
SubsystemBrowserUtils.cpp  
   // flags no longer need to be added in 5.1.1, throws warning, so the Engine just refuses to enable the plugin.
   ADD_FLAG(CLASS_NoExport);
   ADD_FLAG(CLASS_CustomConstructor);

Market lists plugin as compatible up to 5.0 so is out of step.

**Comment by aquanox** [comment]
Fixed in 1.2.1
